### ISSUE TITLE
Issues while editing profile, adding links

### ISSUE THREAD

**Issue by s-a-m** [CRESS-Surrey/cress_website_code#47]
I edited my profile and saved it successfully with no issues. Afterwards, I tried to add a link to http://p2pvalue.eu. While adding the link (using wysiwyg filter), suddently an Ajax error 404 popped out, twice... closing it allowed me to continue (my apologies, I didn't copied the text). It allowed me to add the link. However, it linked by default a relative path (relative to cress.soc.surrey.../p2pvalue.eu) instead an absolute path (http://p2pvalue.eu). I then tried to edit the hyperlink (selecting the http protocol), and when I saved afterwards the following error appeared (*). Coming backwards in the browser and saving again made it worked (with correct link). 

(*):
Error
The website encountered an unexpected error. Please try again later.
Error message

    Warning: PDO::__construct(): MySQL server has gone away in DatabaseConnection->__construct() (line 307 of /Volumes/Documents/VirtualSites/cress/web/includes/database/database.inc).
    PDOException: SQLSTATE[HY000] [2002] Connection refused in lock_may_be_available() (line 167 of /Volumes/Documents/VirtualSites/cress/web/includes/lock.inc).

**Comment by drozas** [comment]
Hello @s-a-m 

Thanks for reporting this!

I suspect the AJAX issue is related with the problems with the DBMS at Dusty, which affects the sites periodically (Nigel is already aware of it).

Regarding the additions of absolute links in the Biography field (using the WYSIWYG editor), you need to select:
- Link Type: URL
- Protocol: http://
- Link: p2pvalue.eu

Looking at the text, it is working perfectly. So I suspect this was due again to the general error related to the MySQL server at dusty (although the changes were indeed properly saved).

Hope this helps!

David

**Comment by drozas** [comment]
This seems to be related to the DB server error. Marking this as closed.
