### ISSUE TITLE
ABM course archive

### ISSUE THREAD

**Issue by drozas** [CRESS-Surrey/cress_website_code#56]
Dear David, 

Not sure that it is you I need to ask - but I would like to have an archive where participants in the ABM course can download the slides from. Preferably with a general username and password (so just one for all downloaders). Would that be possible to do under the CRESS teaching ABM course tab?

Thanks a lot - 

Corinna

**Comment by drozas** [comment]
To-do: test and prepare answer: wiki page + special role?

**Comment by drozas** [comment]
Check https://www.drupal.org/project/private_files_download_permission

**Comment by drozas** [comment]
Reply to refine requirements:
Hello Corinna!

It is possible to do it in Drupal, of course! I would need to clarify, however, a bit more some of the requirements:

    Are there going to be different archives/pages for different editions of the course? If so, should students attending certain edition only be able to access materials from that one?
    Do we need to make the page private, or also all the materials that will be uploaded to it (the default behaviour of Drupal for uploaded files is to make everything public, which could be linked by Google or other bots)?
    What formats and estimated sizes would have the slides (approximately)?

I have created an issue at the Github repository to track all this at https://github.com/CRESS-Surrey/cress_website_code/issues/56

Best,

David

**Comment by corinnaelsenbroich** [comment]
Are there going to be different archives/pages for different editions of the course? If so, should students attending certain edition only be able to access materials from that one?

- Each run has slightly different slides so they would need to differ. However, they only need to be available for a short time and for the next round the new slides could just be uploaded and a new password given.

Do we need to make the page private, or also all the materials that will be uploaded to it (the default behaviour of Drupal for uploaded files is to make everything public, which could be linked by Google or other bots)?

- They should be private. 

What formats and estimated sizes would have the slides (approximately)?

- The slides would be pdf and overall it’s about 100 MB.

**Comment by drozas** [comment]
Successfully tested locally:
- Creating new Content Type setting it for private download
- Created a new role for abm course
- Created a new user for it
- It was necessary to install an extra contrib module to take care of the granularity of the viewing permissions

**Comment by drozas** [comment]
TO-DO:
- Deploy and test changes in production
- Provide admin permissions to @corinnaelsenbroich 
- Carry out test with private files
- Prepare instructions on how to create and upload files

**Comment by drozas** [comment]
Successfully deployed and tested!

**Comment by drozas** [comment]
Hello Corinna,

I have developed and deployed the changes regarding the web archive for the ABM course slides. This entailed the creation of a new content type, role, etc (more details at https://github.com/CRESS-Surrey/cress_website_code/issues/56 in case you are interested).

I have created a new page of type "ABM course resources page " at http://cress.soc.surrey.ac.uk/web/abm-course-resources You can just upload the contents and files into it. The system is extensible, so in future editions of the course you could decide whether to override this page, or create a new one "Content-> Add Content-> ABM course resources page".

The page works in a similar way as the "wiki page" content type in CRESS (the one used for http://cress.soc.surrey.ac.uk/web/teaching/abm-short-course):

    Title
    Body: you can include here the links to the resources you upload by using the "link" button of the WYSIWYG editor. I have included an example. An easy way to do this is copying and pasting the link of the resource (Right button -> copy link), and then paste it using the "link button" (using link type = URL). I attach an screenshot, but please do not hesitate to let me know if this is unclear.
    Resources: you can upload here all the resources for the course. They will be listed at the bottom as well in a summary view (please, let me know if you prefer me to hide this).

Regarding the access, the page and the files are private. E.g:

    http://cress.soc.surrey.ac.uk/web/abm-course-resources
    http://cress.soc.surrey.ac.uk/web/system/files/abm-resources/pdf-sample.pdf

In order for the students to access the resources, it is necessary to login with the following credentials:

    Visit http://cress.soc.surrey.ac.uk/web/user or follow the link in the bottom of the page
    u: XXXXXXXXXXXXXXXXXXX
    p: XXXXXXXXXXXXXXXXXXX

I assumed one account for students should be enough, but we can create more accounts with those permissions if necessary. Both of you have also administrator permissions on the cress site (I just gave them to you, Corinna), so you have complete access with your previous credentials.

Hope this helps!

David

**Comment by drozas** [comment]
![screenshot from 2016-11-21 13 21 40](https://cloud.githubusercontent.com/assets/1962473/20482755/98045ffa-afee-11e6-8867-10252432e96f.png)
